# @package _group_
_target_: src.algorithm.CSalluneed.CSalluneed
arch: ${arch}
dataset: ${dataset}
num_source_classes: ${datamodule.num_source_classes}
learning_rate: ${learning_rate}
weight_decay: ${weight_decay}
pretrained: ${pretrained}
pred_save_path: ${output_dir}
max_epochs: ${max_epochs}
work_dir: ${work_dir}
hash: ${logger.group}
pretrained_model_dir: ${pretrained_model_dir}
seed: ${seed}
pretrained_model_path: ${pretrained_model_path}
ood_class_ratio: ${ood_class_ratio}
constrained_penalty: ${constrained_penalty}
fraction_ood_class: ${fraction_ood_class}
use_superclass: ${use_superclass}
data_dir: ${data_dir}
use_labels: ${use_labels}
clip: ${clip}
ood_class: ${ood_class}
optimizer: ${optimizer}