_target_: src.algorithm.recall_at_fpr.TrainRAtF
arch: ${arch}
dataset: ${dataset}
num_source_classes: ${datamodule.num_source_classes}
learning_rate: ${learning_rate}
weight_decay: ${weight_decay}
dual_learning_rate: ${dual_learning_rate}
pred_save_path: ${output_dir}
pretrained: ${pretrained}
max_epochs: ${max_epochs}
work_dir: ${work_dir}
hash: ${logger.group}
seed: ${seed}
separate: ${separate}