# @package _group_
_target_: src.algorithm.shot_im.SHOT_IM
arch: ${arch}
dataset: ${dataset}
num_source_classes: ${datamodule.num_source_classes}
learning_rate: ${learning_rate}
weight_decay: ${weight_decay}
dual_learning_rate: ${dual_learning_rate}
target_recall: ${target_recall}
logit_multiplier: ${logit_multiplier}
precision_confidence: ${precision_confidence}
target_precision: ${target_precision}
pred_save_path: ${output_dir}
pretrained: ${pretrained}
max_epochs: ${max_epochs}
warmup_epochs: ${warmup_epochs}
warmup_patience: ${warmup_patience}
work_dir: ${work_dir}
hash: ${logger.group}
seed: ${seed}
separate: ${separate}
pretrained_model_dir: ${pretrained_model_dir}
pretrained_model_path: ${pretrained_model_path}
device: ${device}
mode: ${mode}
ood_class_ratio: ${ood_class_ratio}
ood_class: ${ood_class}
constrained_penalty: ${constrained_penalty}
save_model_path: ${save_model_path}
fraction_ood_class: ${fraction_ood_class}
use_superclass: ${use_superclass}
data_dir: ${data_dir}
use_labels: ${use_labels}
clip: ${clip}
optimizer: ${optimizer}